### student upload
post http://localhost:35000/signUp
content-type: application/json

{
    "username" : "test1",
    "email" : "hjkjasdkajhsdads",
    "tel" : "0888888888",
}




###
post http://localhost:35000/register
content-type: application/json

{
    "username" : "moyanyo",
    "name" : "suphakorn",
    "lastname" :"srinak",
    "password" : "12345",
    "role" : "1",
    "id_card" : "1987600854342",
    "email" : "61022540@up.ac.th",
    "tell" : "0999999999"
}


###
post http://localhost:35000/login
content-type: application/json

{
    "username" : "windoss",
    "password" : "12345"
    
}

####
post http://localhost:35000/addcar
content-type: application/json

{
    "License_plate" : "454465",
    "seat" : "15"
    
}

####
post http://localhost:35000/addcarmacht
content-type: application/json

{
    "car_id" : "1",
    "driver_id" : "1",
     "date" : "11/2/64"
}

####
post http://localhost:35000/updatecar
content-type: application/json

{
    "License_plate" : "1231",
    "seat" : "15",
     "car_id" : "1"
}

####
post http://localhost:35000/updatecarmatch
content-type: application/json

{
    "driver_id" : "1231",
    "car_id" : "1",
    "date" : "2021/7/21",
    "carmatch" : "3"
    
}


####
delete http://localhost:35000/deletecar
content-type: application/json

{
    "car_id" : "5"
    
    
}
####
get http://localhost:35000/query_location
content-type: application/json

{
    
  
}

####
post http://localhost:35000/addlocation
content-type: application/json

{
    "carmatch" : "667",
    "lat" : "192.1111",
    "lng" : "192.2222"
   
    
}

####
post http://localhost:35000/selectstar
content-type: application/json

{
    "driver_id" : "3",
    "date" : "2021/07/21"
   
    
}